// app/lifecycles/page.tsx — Index of every shipped studio's
// auto-generated FSM lifecycle diagram. Reads
// website/public/fsm-diagrams/<studio>.mmd at build time and lists
// each studio with a link to its detail page.
//
// The .mmd files are regenerated by
// packages/haiku/scripts/export-fsm-diagrams.mjs from the xstate
// machine config + StudioConfig. Whenever a studio's STAGE.md /
// hats / fix-hats / review-agents change, the diagrams regenerate
// (also wired into the haiku package's prebuild step).

import { readdirSync, readFileSync, statSync } from "node:fs"
import type { Metadata } from "next"
import Link from "next/link"
import { join } from "node:path"

export const metadata: Metadata = {
	title: "Studio Lifecycles - H·AI·K·U",
	description:
		"Auto-generated state diagrams for every H·AI·K·U studio's lifecycle — derived from the xstate machine config.",
}

interface StudioSummary {
	slug: string
	stageCount: number
	hatCount: number
	body: string
}

function listStudios(): StudioSummary[] {
	const diagramsDir = join(
		process.cwd(),
		"public",
		"fsm-diagrams",
	)
	let entries: string[] = []
	try {
		entries = readdirSync(diagramsDir).filter((f) => f.endsWith(".mmd"))
	} catch {
		return []
	}
	const out: StudioSummary[] = []
	for (const file of entries) {
		const slug = file.replace(/\.mmd$/, "")
		const path = join(diagramsDir, file)
		try {
			statSync(path)
			const body = readFileSync(path, "utf8")
			// Cheap structural counts — match the literal block markers
			// the exporter emits. `state X {` for each stage; we sum
			// hat enumeration by counting the `_execute_*` ids.
			const stageCount = (body.match(/^  state \w+ \{$/gm) ?? []).length
			const hatCount = (body.match(/_execute_\w+ -->/g) ?? []).length
			out.push({ slug, stageCount, hatCount, body })
		} catch {
			/* skip unreadable entries */
		}
	}
	return out.sort((a, b) => a.slug.localeCompare(b.slug))
}

export default function LifecyclesPage() {
	const studios = listStudios()

	return (
		<div className="mx-auto max-w-3xl px-6 py-12">
			<h1 className="mb-4 text-4xl font-bold tracking-tight">
				Studio Lifecycles
			</h1>
			<p className="mb-2 text-lg text-stone-600 dark:text-stone-400">
				Every shipped studio's FSM lifecycle as a Mermaid state diagram —
				auto-generated from the xstate machine config.
			</p>
			<p className="mb-8 text-sm text-stone-500 dark:text-stone-500">
				Diagrams enumerate every stage, every hat sequence inside execute,
				and every (bolt × fix-hat) combination inside review_fix.
			</p>

			{studios.length === 0 ? (
				<div className="rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900 dark:border-amber-800 dark:bg-amber-950/30 dark:text-amber-200">
					No diagrams found. Run{" "}
					<code className="rounded bg-amber-100 px-1 dark:bg-amber-900">
						bun run --cwd packages/haiku export:fsm-diagrams
					</code>{" "}
					to generate them.
				</div>
			) : (
				<div className="grid gap-3">
					{studios.map((s) => (
						<Link
							key={s.slug}
							href={`/lifecycles/${s.slug}`}
							className="block rounded-lg border border-stone-200 bg-white p-4 transition-colors hover:border-blue-400 hover:bg-blue-50 dark:border-stone-700 dark:bg-stone-900 dark:hover:border-blue-500 dark:hover:bg-blue-950/20"
						>
							<div className="font-mono text-base font-semibold text-stone-900 dark:text-stone-100">
								{s.slug}
							</div>
							<div className="mt-1 text-xs text-stone-500 dark:text-stone-400">
								{s.stageCount} stages · {s.hatCount} hat transitions
							</div>
						</Link>
					))}
				</div>
			)}
		</div>
	)
}
